package View;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rao.mah
 */
import Models.UserProfile;
import Verifiers.RegexVerifier;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.image.BufferedImage;

import java.io.File;
import java.io.IOException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.imageio.ImageIO;

import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
public class HomeJFrame extends javax.swing.JFrame {

    /**
     * Creates new form HomeJFrame
     */
    public HomeJFrame() {
        initUserProfile();
        initComponents();
        initImagePicker();
        setUpVerifiers();
        setUpNotEditableState();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        jMenu1 = new javax.swing.JMenu();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        basicInfoPanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        nameEntryField = new javax.swing.JTextField();
        areaLabel = new javax.swing.JLabel();
        areaEntryField = new javax.swing.JTextField();
        dobLabel = new javax.swing.JLabel();
        telephoneLabel = new javax.swing.JLabel();
        telephoneEntryField = new javax.swing.JTextField();
        faxLabel = new javax.swing.JLabel();
        faxEntryField = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        emailEntryField = new javax.swing.JTextField();
        imagePreviewLabel = new javax.swing.JLabel();
        imageSelectButton = new javax.swing.JButton();
        dateEntryChooser = new com.toedter.calendar.JDateChooser();
        otherDetailsPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        ssnEntryField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        medicalEntryField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        hpbnEntryField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        accountEntryField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        vehicleEntryField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        licenseEntryField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        deviceIdEntryField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        linkedinLabel = new javax.swing.JLabel();
        linkedinEntryField = new javax.swing.JTextField();
        uidEntryField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        ipEntryField = new javax.swing.JTextField();
        savebutton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        basicInfoPanel1 = new javax.swing.JPanel();
        nameLabel1 = new javax.swing.JLabel();
        nameEntryField1 = new javax.swing.JTextField();
        areaLabel1 = new javax.swing.JLabel();
        areaEntryField1 = new javax.swing.JTextField();
        dobLabel1 = new javax.swing.JLabel();
        dobEntryField1 = new javax.swing.JTextField();
        telephoneLabel1 = new javax.swing.JLabel();
        telephoneEntryField1 = new javax.swing.JTextField();
        faxLabel1 = new javax.swing.JLabel();
        faxEntryField1 = new javax.swing.JTextField();
        emailLabel1 = new javax.swing.JLabel();
        emailEntryField1 = new javax.swing.JTextField();
        imagePreviewLabel1 = new javax.swing.JLabel();
        otherDetailsPanel1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        ssnEntryField1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        medicalEntryField1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        hpbnEntryField1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        accountEntryField1 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        vehicleEntryField1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        licenseEntryField1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        deviceIdEntryField1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        linkedinLabel1 = new javax.swing.JLabel();
        linkedinEntryField1 = new javax.swing.JTextField();
        uidEntryField1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        ipEntryField1 = new javax.swing.JTextField();

        jLabel14.setText("jLabel14");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        basicInfoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Basic Information"));

        nameLabel.setText("Name:");

        nameEntryField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameEntryFieldFocusLost(evt);
            }
        });
        nameEntryField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameEntryFieldActionPerformed(evt);
            }
        });
        nameEntryField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameEntryFieldKeyReleased(evt);
            }
        });

        areaLabel.setText("Area:");

        dobLabel.setText("Date of Birth:");

        telephoneLabel.setText("Telephone Number:");

        faxLabel.setText("FAX number:");

        emailLabel.setText("Email addresses:");

        imagePreviewLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        imageSelectButton.setText("Select Photo");
        imageSelectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageSelectButtonActionPerformed(evt);
            }
        });
        imageSelectButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                imageSelectButtonKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout basicInfoPanelLayout = new javax.swing.GroupLayout(basicInfoPanel);
        basicInfoPanel.setLayout(basicInfoPanelLayout);
        basicInfoPanelLayout.setHorizontalGroup(
            basicInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basicInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(basicInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(telephoneLabel)
                    .addComponent(faxLabel)
                    .addComponent(nameLabel)
                    .addComponent(dobLabel)
                    .addComponent(emailLabel)
                    .addComponent(areaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(basicInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(areaEntryField, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                    .addComponent(emailEntryField)
                    .addComponent(nameEntryField)
                    .addComponent(telephoneEntryField)
                    .addComponent(faxEntryField)
                    .addComponent(dateEntryChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(basicInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(imagePreviewLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(imageSelectButton, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
                .addContainerGap())
        );
        basicInfoPanelLayout.setVerticalGroup(
            basicInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basicInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(basicInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(basicInfoPanelLayout.createSequentialGroup()
                        .addGroup(basicInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameLabel)
                            .addComponent(nameEntryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(basicInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateEntryChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(basicInfoPanelLayout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(dobLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(basicInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailEntryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(basicInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(areaLabel)
                            .addComponent(areaEntryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(basicInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(telephoneEntryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telephoneLabel)))
                    .addComponent(imagePreviewLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(basicInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(basicInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(faxEntryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(faxLabel))
                    .addComponent(imageSelectButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        otherDetailsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Other Details"));

        jLabel7.setText("Social Security number:");

        ssnEntryField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssnEntryFieldActionPerformed(evt);
            }
        });

        jLabel8.setText("Medical record number:");

        jLabel9.setText("Health Plan Beneficiary Number:");

        jLabel10.setText("Bank Account Number:");

        jLabel11.setText("Vehicle Number:");

        jLabel12.setText("License Number:");

        jLabel13.setText("Device Identifier Number:");

        deviceIdEntryField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deviceIdEntryFieldActionPerformed(evt);
            }
        });

        jLabel15.setText("Unique Identifier Number:");

        linkedinLabel.setText("LinkedIn:");

        jLabel18.setText("Internet Protocol Address:");

        javax.swing.GroupLayout otherDetailsPanelLayout = new javax.swing.GroupLayout(otherDetailsPanel);
        otherDetailsPanel.setLayout(otherDetailsPanelLayout);
        otherDetailsPanelLayout.setHorizontalGroup(
            otherDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(otherDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(otherDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(linkedinLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(otherDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(otherDetailsPanelLayout.createSequentialGroup()
                        .addGroup(otherDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ssnEntryField, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                            .addComponent(hpbnEntryField)
                            .addComponent(licenseEntryField))
                        .addGap(2, 2, 2))
                    .addComponent(linkedinEntryField)
                    .addComponent(uidEntryField, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(otherDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(otherDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(accountEntryField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                    .addComponent(medicalEntryField)
                    .addComponent(deviceIdEntryField)
                    .addComponent(ipEntryField)
                    .addComponent(vehicleEntryField))
                .addContainerGap())
        );
        otherDetailsPanelLayout.setVerticalGroup(
            otherDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(otherDetailsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(otherDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(linkedinEntryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(linkedinLabel)
                    .addComponent(jLabel18)
                    .addComponent(ipEntryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(otherDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uidEntryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(deviceIdEntryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(otherDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ssnEntryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(medicalEntryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(otherDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(hpbnEntryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accountEntryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(otherDetailsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(licenseEntryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(vehicleEntryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        savebutton.setText("SAVE");
        savebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebuttonActionPerformed(evt);
            }
        });
        savebutton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                savebuttonKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(otherDetailsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(basicInfoPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(savebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(basicInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(otherDetailsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(savebutton)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Fill Form", jPanel1);

        basicInfoPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Basic Information"));

        nameLabel1.setText("Name:");

        nameEntryField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameEntryField1FocusLost(evt);
            }
        });
        nameEntryField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameEntryField1ActionPerformed(evt);
            }
        });
        nameEntryField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameEntryField1KeyReleased(evt);
            }
        });

        areaLabel1.setText("Area:");

        dobLabel1.setText("Date of Birth:");

        telephoneLabel1.setText("Telephone Number:");

        faxLabel1.setText("FAX number:");

        emailLabel1.setText("Email addresses:");

        javax.swing.GroupLayout basicInfoPanel1Layout = new javax.swing.GroupLayout(basicInfoPanel1);
        basicInfoPanel1.setLayout(basicInfoPanel1Layout);
        basicInfoPanel1Layout.setHorizontalGroup(
            basicInfoPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basicInfoPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(basicInfoPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(telephoneLabel1)
                    .addComponent(faxLabel1)
                    .addComponent(nameLabel1)
                    .addComponent(dobLabel1)
                    .addComponent(emailLabel1)
                    .addComponent(areaLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(basicInfoPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(areaEntryField1, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                    .addComponent(emailEntryField1)
                    .addComponent(dobEntryField1)
                    .addComponent(nameEntryField1)
                    .addComponent(telephoneEntryField1)
                    .addComponent(faxEntryField1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imagePreviewLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        basicInfoPanel1Layout.setVerticalGroup(
            basicInfoPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basicInfoPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(basicInfoPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imagePreviewLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(basicInfoPanel1Layout.createSequentialGroup()
                        .addGroup(basicInfoPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameLabel1)
                            .addComponent(nameEntryField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(basicInfoPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dobLabel1)
                            .addComponent(dobEntryField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(basicInfoPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailEntryField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(basicInfoPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(areaLabel1)
                            .addComponent(areaEntryField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(basicInfoPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(telephoneEntryField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telephoneLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(basicInfoPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(faxEntryField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(faxLabel1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        otherDetailsPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Other Details"));

        jLabel16.setText("Social Security number:");

        ssnEntryField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssnEntryField1ActionPerformed(evt);
            }
        });

        jLabel17.setText("Medical record number:");

        jLabel19.setText("Health Plan Beneficiary Number:");

        jLabel20.setText("Bank Account Number:");

        jLabel21.setText("Vehicle Number:");

        jLabel22.setText("License Number:");

        jLabel23.setText("Device Identifier Number:");

        deviceIdEntryField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deviceIdEntryField1ActionPerformed(evt);
            }
        });

        jLabel24.setText("Unique Identifier Number:");

        linkedinLabel1.setText("LinkedIn:");

        jLabel25.setText("Internet Protocol Address:");

        javax.swing.GroupLayout otherDetailsPanel1Layout = new javax.swing.GroupLayout(otherDetailsPanel1);
        otherDetailsPanel1.setLayout(otherDetailsPanel1Layout);
        otherDetailsPanel1Layout.setHorizontalGroup(
            otherDetailsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(otherDetailsPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(otherDetailsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(linkedinLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(otherDetailsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(otherDetailsPanel1Layout.createSequentialGroup()
                        .addGroup(otherDetailsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ssnEntryField1, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(hpbnEntryField1)
                            .addComponent(licenseEntryField1))
                        .addGap(2, 2, 2))
                    .addComponent(linkedinEntryField1)
                    .addComponent(uidEntryField1, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(otherDetailsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(otherDetailsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(accountEntryField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addComponent(medicalEntryField1)
                    .addComponent(deviceIdEntryField1)
                    .addComponent(ipEntryField1)
                    .addComponent(vehicleEntryField1))
                .addContainerGap())
        );
        otherDetailsPanel1Layout.setVerticalGroup(
            otherDetailsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(otherDetailsPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(otherDetailsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(linkedinEntryField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(linkedinLabel1)
                    .addComponent(jLabel25)
                    .addComponent(ipEntryField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(otherDetailsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uidEntryField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(deviceIdEntryField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(otherDetailsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(ssnEntryField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(medicalEntryField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(otherDetailsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(hpbnEntryField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accountEntryField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(otherDetailsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(licenseEntryField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(vehicleEntryField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(otherDetailsPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(basicInfoPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addComponent(basicInfoPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(otherDetailsPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );

        jTabbedPane1.addTab("View Form", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void savebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebuttonActionPerformed
        // TODO add your handling code here:
        validateAndSaveUserData();
    }//GEN-LAST:event_savebuttonActionPerformed

    
    private void savebuttonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_savebuttonKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_savebuttonKeyPressed

    private void imageSelectButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_imageSelectButtonKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_imageSelectButtonKeyPressed

    private void imageSelectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageSelectButtonActionPerformed
        showImagePicker();     
    }//GEN-LAST:event_imageSelectButtonActionPerformed

    private void nameEntryFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameEntryFieldKeyReleased

    }//GEN-LAST:event_nameEntryFieldKeyReleased

    private void nameEntryFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameEntryFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameEntryFieldActionPerformed

    private void nameEntryFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameEntryFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_nameEntryFieldFocusLost

    private void deviceIdEntryFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deviceIdEntryFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deviceIdEntryFieldActionPerformed

    private void ssnEntryFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssnEntryFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ssnEntryFieldActionPerformed

    private void nameEntryField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameEntryField1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_nameEntryField1FocusLost

    private void nameEntryField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameEntryField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameEntryField1ActionPerformed

    private void nameEntryField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameEntryField1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_nameEntryField1KeyReleased

    private void ssnEntryField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssnEntryField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ssnEntryField1ActionPerformed

    private void deviceIdEntryField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deviceIdEntryField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deviceIdEntryField1ActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        // TODO add your handling code here:
        if (jTabbedPane1.getSelectedIndex() == 1) {
            loadSaveUserFromModel();
        }
    }//GEN-LAST:event_jTabbedPane1StateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeJFrame().setVisible(true);
            }
        });
    }
    
    private void initUserProfile() {
        this.userProfile = new UserProfile();
    }
    
    private void initImagePicker() {
        this.filePicker = new JFileChooser();
    }
    
    private void setUpVerifiers() {
        
        nameVerifier = new RegexVerifier(nameEntryField, "^[a-zA-Z]{0,30}$", "name");
        nameEntryField.setInputVerifier(nameVerifier);
        
        emailVerifier = new RegexVerifier(emailEntryField, "^[a-zA-Z0-9]{0,30}[@][a-zA-Z0-9]{0,10}[.][a-zA-Z]{0,5}$", "email");
        emailEntryField.setInputVerifier(emailVerifier);
        
        areaVerifier = new RegexVerifier(areaEntryField, "^[a-zA-Z]{0,30}$", "area");
        areaEntryField.setInputVerifier(areaVerifier);
        
        telephoneVerifier = new RegexVerifier(telephoneEntryField, "^[0-9]{0,10}$", "telephone");
        telephoneEntryField.setInputVerifier(telephoneVerifier);
        
        faxVerifier = new RegexVerifier(faxEntryField, "^[0-9]{0,10}$", "fax");
        faxEntryField.setInputVerifier(faxVerifier);
        
        linkedinVerifier = new RegexVerifier(linkedinEntryField, "^https?:\\/\\/(www\\.)?[-a-zA-Z0-9@:%._\\+~#=]{1,256}\\.[a-zA-Z0-9()]{1,6}\\b([-a-zA-Z0-9()@:%_\\+.~#?&//=]*)$", "linkedin");
        linkedinEntryField.setInputVerifier(linkedinVerifier);
        
        ipVerifier = new RegexVerifier(ipEntryField, "^\\b\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\b$", "ip adress");
        ipEntryField.setInputVerifier(ipVerifier);
        
        uinVerifier = new RegexVerifier(uidEntryField, "^[0-9]{0,15}$", "Unique identifier number");
        uidEntryField.setInputVerifier(uinVerifier);
        
        dinVerifier = new RegexVerifier(deviceIdEntryField, "^[0-9]{0,15}$", "Device identifier number");
        deviceIdEntryField.setInputVerifier(dinVerifier);
        
        ssnVerifier = new RegexVerifier(ssnEntryField, "^[0-9]{0,15}$", "Social security number");
        ssnEntryField.setInputVerifier(ssnVerifier);
        
        mrnVerifier = new RegexVerifier(medicalEntryField, "^[a-zA-Z0-9]{0,15}$", "Medical record number");
        medicalEntryField.setInputVerifier(mrnVerifier);
        
        hpbnVerifier = new RegexVerifier(hpbnEntryField, "^[a-zA-Z0-9]{0,15}$", "Health plan benficiary number");
        hpbnEntryField.setInputVerifier(hpbnVerifier);
        
        accountVerifier = new RegexVerifier(accountEntryField, "^[0-9]{0,15}$", "Account number");
        accountEntryField.setInputVerifier(accountVerifier); 
        
        licenseVerifier = new RegexVerifier(licenseEntryField, "^[a-zA-Z0-9]{0,15}$", "Licence number");
        licenseEntryField.setInputVerifier(licenseVerifier); 
        
        vehichleVerifier = new RegexVerifier(vehicleEntryField, "^[a-zA-Z0-9]{0,15}$", "Vechicle number");
        vehicleEntryField.setInputVerifier(vehichleVerifier);        
        
    }
    
    private void setUpNotEditableState() {
        nameEntryField1.setEditable(false);
        // Make them non editabe;
    }
    
    private void showImagePicker() {
        this.temproryImage = null;
        FileNameExtensionFilter fnef =  new FileNameExtensionFilter("IMAGES","png","jpg","jpeg");
        filePicker.addChoosableFileFilter(fnef);
        int saveDialogState =  filePicker.showSaveDialog(this);

        if(saveDialogState == JFileChooser.APPROVE_OPTION) {
            File selectedImageFile = filePicker.getSelectedFile();
            try {
                this.temproryImage = ImageIO.read(selectedImageFile);
                ImageIcon imageIcon = new ImageIcon(temproryImage); 
                Image scaledImage  = imageIcon.getImage().getScaledInstance(imagePreviewLabel.getWidth() - 40,imagePreviewLabel.getHeight() - 40, Image.SCALE_SMOOTH);
                imagePreviewLabel.setIcon(new ImageIcon(scaledImage));
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Image couldn't be loaded");
            }
        }
    }
    
    private void validateAndSaveUserData() {
        if (!nameVerifier.isValid()) {
            JOptionPane.showMessageDialog(this, "Inavlid name", "Validation failed ", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (dateEntryChooser.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Inavlid date of birth", "Validation failed ", JOptionPane.ERROR_MESSAGE);
            return;
        }
            
        if (!emailVerifier.isValid()) {
            JOptionPane.showMessageDialog(this, "Inavlid email", "Validation failed ", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (!areaVerifier.isValid()) {
            JOptionPane.showMessageDialog(this, "Inavlid area", "Validation failed ", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (!telephoneVerifier.isValid())  {
            JOptionPane.showMessageDialog(this, "Inavlid telephone", "Validation failed ", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (!faxVerifier.isValid())  {
            JOptionPane.showMessageDialog(this, "Inavlid fax", "Validation failed ", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (!linkedinVerifier.isValid())  {
            JOptionPane.showMessageDialog(this, "Inavlid linkedin", "Validation failed ", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (!ipVerifier.isValid())  {
            JOptionPane.showMessageDialog(this, "Inavlid ip", "Validation failed ", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (!uinVerifier.isValid())  {
            JOptionPane.showMessageDialog(this, "Inavlid unique indentidier number", "Validation failed ", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (!dinVerifier.isValid())  {
            JOptionPane.showMessageDialog(this, "Inavlid device id", "Validation failed ", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (!ssnVerifier.isValid())  {
            JOptionPane.showMessageDialog(this, "Inavlid SSN", "Validation failed ", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (!mrnVerifier.isValid())  {
            JOptionPane.showMessageDialog(this, "Inavlid mrn", "Validation failed ", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (!hpbnVerifier.isValid())  {
            JOptionPane.showMessageDialog(this, "Inavlid hpbn", "Validation failed ", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (!accountVerifier.isValid())  {
            JOptionPane.showMessageDialog(this, "Inavlid account", "Validation failed ", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (!licenseVerifier.isValid())  {
            JOptionPane.showMessageDialog(this, "Inavlid license number", "Validation failed ", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (!vehichleVerifier.isValid())  {
            JOptionPane.showMessageDialog(this, "Inavlid vehichle number", "Validation failed ", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (this.temproryImage == null) {
            JOptionPane.showMessageDialog(this, "Please add image", "Validation failed ", JOptionPane.ERROR_MESSAGE);
            return;
        }
        saveToModel();
        clearEntryField();
        JOptionPane.showMessageDialog(this, "User data have been save", "Success", JOptionPane.INFORMATION_MESSAGE);
    }
    
    private void clearEntryField() {
        nameEntryField.setText("");
        imagePreviewLabel.setText("");
        // clear all entry text field
    }
    
    private void saveToModel() {
        this.userProfile.setName(nameEntryField.getText());
        this.userProfile.setImage(temproryImage);
//        Date dob = this.dateEntryChooser.getDate();
        // save other fields
    }
    
    private void loadSaveUserFromModel() {
        nameEntryField1.setText(userProfile.getName());
        if (userProfile.getImage() != null) {
            ImageIcon imageIcon = new ImageIcon(userProfile.getImage()); 
            Image scaledImage  = imageIcon.getImage().getScaledInstance(imagePreviewLabel1.getWidth() - 40,imagePreviewLabel1.getHeight() - 40, Image.SCALE_SMOOTH);
            imagePreviewLabel1.setIcon(new ImageIcon(scaledImage));
        }
       
        // Set all data
    }
    
    
    // Verifiers
    private RegexVerifier nameVerifier;
    private RegexVerifier emailVerifier;
    private RegexVerifier areaVerifier;
    private RegexVerifier telephoneVerifier;
    private RegexVerifier faxVerifier;
    
    private RegexVerifier linkedinVerifier;
    private RegexVerifier ipVerifier;
    private RegexVerifier uinVerifier;
    private RegexVerifier dinVerifier;
    private RegexVerifier ssnVerifier;
    private RegexVerifier mrnVerifier;
    private RegexVerifier hpbnVerifier;
    private RegexVerifier accountVerifier;
    private RegexVerifier licenseVerifier;
    private RegexVerifier vehichleVerifier;
    
    // Data model
    private UserProfile userProfile;
    
    // Image picker
    private JFileChooser filePicker;
    private BufferedImage temproryImage;
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accountEntryField;
    private javax.swing.JTextField accountEntryField1;
    private javax.swing.JTextField areaEntryField;
    private javax.swing.JTextField areaEntryField1;
    private javax.swing.JLabel areaLabel;
    private javax.swing.JLabel areaLabel1;
    private javax.swing.JPanel basicInfoPanel;
    private javax.swing.JPanel basicInfoPanel1;
    private com.toedter.calendar.JDateChooser dateEntryChooser;
    private javax.swing.JTextField deviceIdEntryField;
    private javax.swing.JTextField deviceIdEntryField1;
    private javax.swing.JTextField dobEntryField1;
    private javax.swing.JLabel dobLabel;
    private javax.swing.JLabel dobLabel1;
    private javax.swing.JTextField emailEntryField;
    private javax.swing.JTextField emailEntryField1;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel emailLabel1;
    private javax.swing.JTextField faxEntryField;
    private javax.swing.JTextField faxEntryField1;
    private javax.swing.JLabel faxLabel;
    private javax.swing.JLabel faxLabel1;
    private javax.swing.JTextField hpbnEntryField;
    private javax.swing.JTextField hpbnEntryField1;
    private javax.swing.JLabel imagePreviewLabel;
    private javax.swing.JLabel imagePreviewLabel1;
    private javax.swing.JButton imageSelectButton;
    private javax.swing.JTextField ipEntryField;
    private javax.swing.JTextField ipEntryField1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField licenseEntryField;
    private javax.swing.JTextField licenseEntryField1;
    private javax.swing.JTextField linkedinEntryField;
    private javax.swing.JTextField linkedinEntryField1;
    private javax.swing.JLabel linkedinLabel;
    private javax.swing.JLabel linkedinLabel1;
    private javax.swing.JTextField medicalEntryField;
    private javax.swing.JTextField medicalEntryField1;
    private javax.swing.JTextField nameEntryField;
    private javax.swing.JTextField nameEntryField1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel nameLabel1;
    private javax.swing.JPanel otherDetailsPanel;
    private javax.swing.JPanel otherDetailsPanel1;
    private javax.swing.JButton savebutton;
    private javax.swing.JTextField ssnEntryField;
    private javax.swing.JTextField ssnEntryField1;
    private javax.swing.JTextField telephoneEntryField;
    private javax.swing.JTextField telephoneEntryField1;
    private javax.swing.JLabel telephoneLabel;
    private javax.swing.JLabel telephoneLabel1;
    private javax.swing.JTextField uidEntryField;
    private javax.swing.JTextField uidEntryField1;
    private javax.swing.JTextField vehicleEntryField;
    private javax.swing.JTextField vehicleEntryField1;
    // End of variables declaration//GEN-END:variables
}
